// ==UserScript==
// @name         TETR.IO中文翻译
// @namespace    https://github.com/huanmieSAA/iotranslate
// @version      1.0
// @description  将TETR.IO中的内容翻译成中文并自动刷新保证翻译内容基本完成，对性能可能有一点影响 鸣谢：mrz,xb以及各位群友
// @match        https://*.tetr.io/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // 定义文本映射表
    const textMap = {
        //初始界面文本
      "JOIN": "加入",
      "total players": "总玩家数",
      "games played": "对局场数",
      "hours played": "总游戏时长",
      "welcome to TETR.IO": "欢迎来到TETR.IO",
      "open in": "打开",
      "DESKTOP": "桌面版",
      "GET": "获取",
      "puzzle together in this modern yet familiar online stacker. play against friends and foes all over the world, or claim a spot on the leaderboards - the stacker future is yours!": "欢迎游玩这款熟悉的现代方块游戏。与世界各地的朋友和对手对战，在排行榜上占据一席之地——方块的未来在您手中！",
      "enter a username to join, or leave it blank to get a random one": "输入用户名登录，或留空生成随机用户名",
      "by joining, you accept the": "加入即表示您接受",
      "terms of use": "使用条款",
      "privacy policy": "隐私政策",
      "and": "和",
      "rules": "规则",
      "TETR.IO is in ALPHA. please report bugs when you see them!": "TETR.IO 处于 ALPHA 阶段，请在发现问题时报告错误！",
        //注册相关文本
      "want to join?": "想要加入游戏吗",
      "the nickname": "这个昵称",
      "hasn't been registered. do you want to claim it as yours, or play anonymously? you won't be able to submit scores to the leaderboards or play in matchmaking when anonymous.": "没有被注册。请问你是想把它作为你的账号，还是进行匿名游戏？匿名时，你将无法向排行榜提交分数或参加比赛。",
      "stay ANONYMOUS": "保持匿名",
      "REGISTER": "注册",
      "let's make things official": "让我们正式开始吧",
      "to register, please choose a password for yourself": "想要注册，请输入密码",
        //登录相关文本
      "good to see you again!": "很高兴再次见到你",
      "the username": "这个用户名",
      "is registered. please enter your password to log in": "是注册了的，输入密码来登录（如果是你）",
      "I FORGOT": "我忘了！",
      "LOGIN": "登录",
      "forgot your password?": "忘记了您的密码？",
      "if you have an email address associated with your account, you can reset your password by entering your email.": "如果您的账户关联有电子邮箱，您可以通过它来重置密码。",
      "REQUEST RESET": "请求重置密码",
      "password incorrect": "密码错误",
      "is this you?": "这是你吗？",
      "LOG OUT": "退出登录",
      "welcome back to TETR.IO!": "欢迎回到TETR.IO!",
      "are you": "是你",
      "TETR.IO has a policy of": "TETR.IO有一条政策：",
      "one account per person (anonymous accounts excluded)": "每人仅能拥有一个账户（不包括匿名账户）",
      ". making multiple accounts may result in permanent restriction of all your accounts.": ".开设多个账户可能会导致你的所有账户被永久封禁。",
      "read the": "阅读",
      "full policy": "完整的政策",
      "for more info. in doubt, or if you believe your usage of a second account is justified, please": "如果有疑问，或者你有合理理由使用第二个账户，请联系我们。",
      "contact support": "联系支持",
      "I'M NOT MULTIACCOUNTING": "我没有多账户",
      "just to be sure…": "只是为了确定...",
      "SUBMIT": "允许",
      "two-factor authentication": "双重认证",
      "use your authenticator app to get a six-digit code, or use one of your recovery codes.": "使用你的认证器应用程序获得一个六位数的代码，或使用你的一个恢复代码。",
      "reset your password": "重置你的密码",
      "enter a new password to regain access to your account": "输入一个新的密码，重新进入你的账户",
        //删除账号相关文本
      "delete my account": "删除我的账户",
      "DELETE YOUR ACCOUNT?": "删除你的账户？",
      "delete your account": "删除账户",
      "and all attached data?": "和所有关联的数据？",
      "DELETE!": "删除！",
      "this cannot be undone.": "这是不可逆的",
      "THE SONG OF DESTRUCTION CANNOT BE STOPPED.": "毁灭之歌无法停止。",
      "you're certain you want to delete your account? you will lose EVERYTHING, including but not limited to...": "你确定要删除你的账户吗？ 你将失去所有的东西，包括但不限于...",
      "• all your replays": "• 你的所有回放",
      "• all your XP": "• 你的所有经验值",
      "• all your accomplishments": "• 你所有的成就",
      "• all your badges": "• 你所有的徽章",
      "• your TETRA LEAGUE rank": "• 你的TETRA联赛段位",
      "• and more...": "• 等等...",
      "DELETE": "删除",
      "you're absolutely, 100% certain you won't regret DELETING YOUR ACCOUNT FOREVER?": "你绝对、100%确定你不会为删除你的账户而后悔，直到永远？",
      "NO REGRETS!": "不后悔！",
      "FINAL WARNING": "最后的警告",
      "DELETE YOUR ACCOUNT AND ALL ITS DATA FOREVER?": "永远删除你的账户和所有数据？",
      "DELETE MY ACCOUNT": "删除我的账号",
      "DELETING IN": "删除中",
        //主菜单文本
        //多人游戏相关文本
      "MULTIPLAYER": "多人游戏",
      "play online with friends and foes": "和朋友或陌生人进行在线游戏",
        //TETRA联赛相关文本
      "TETRA LEAGUE": "TETRA 联赛",
      "ANONYMOUS USERS MAY NOT ENTER TETRA LEAGUE": "匿名玩家无法参与TETRA联赛",
      "fight players of your skill in ranked duels": "与水平相当的玩家进行参与排名的对决",
      "this user is playing anonymously": "该用户正在匿名游戏",
      "games won": "获胜次数",
      "IN QUEUE -": "排队中 -",
      "IN GAME": "游戏中",
      "ENTER MATCHMAKING": "进入匹配",
      "LEAVING EARLY IS PUNISHED": "中途退出会受到惩罚",
      "HOW DOES IT WORK?": "这个模式是怎么运作的？",
      "enter matchmaking and you will be matched up with a player of similar skill in a game of 1v1 VERSUS.": "加入匹配队伍，匹配成功后，您将和一个水平相似的玩家进行一场1对1的对战。",
      "win games to gain TR and rank up! you must play at least 10 games to see your TR. to get a RANK and enter the GLOBAL LEADERBOARDS, keep playing consistently.": "获胜可以获得TR并晋升段位！您必须至少玩10局才能看到您的TR。要获得段位并进入全球排行榜，请持续进行游戏。",
      "if you leave the game early at any point, you will be awarded a loss. go conquer the ranks!": "在游戏中任意时刻退出将被判负。去挑战排行榜上的其他玩家吧！",
      "LEADERBOARDS": "排行榜",
      "estimated queue time:": "预计等待时间：",
      "GET READY FOR": "对决",
      "THE NEXT BATTLE": "开始",
      "face off against others and rise up through the ranks!": "与他人对决，并获得段位提升！",
        //快速游戏相关文本
      "QUICK PLAY": "快速游戏",
      "jump into a currently ongoing match": "加入正在进行的比赛",
      "CHAT": "聊天",
      "Welcome to Quick Play chat! Please remember to be civil to your opponents - chat is actively monitored.": "欢迎来到快速游戏聊天室！请文明交流——聊天将被实时监控。",
      "left the room": "离开房间",
      "joined the room": "加入房间",
      "disconnected": "断开连接",
      "started the game": "开始游戏",
      "SPECTATING": "旁观中",
      "CURRENTLY INGAME": "正在游戏中",
      "game finished": "游戏结束",
      "welcome to ": "欢迎来到",
      "is a free familiar yet fast-paced online stacker in the same genre as tetris, and played by millions across the globe.": "是一款免费、易上手但快节奏的在线堆叠游戏，与俄罗斯方块同类，拥有数百万全球玩家。",
      "hover for more info!": "把鼠标悬停在这里以获取更多信息！",
      "your currently set keybinds are:": "您当前的按键绑定是：",
      "PLAYING": "游玩",
      "click to switch to SPECTATORS": "点击切换到旁观模式",
      "click to copy url": "点击这里复制链接",
      "EDIT": "退出",
      "you just joined QUICK PLAY - you will play in the next game in this lobby. please wait for the current game to finish. feel free to spectate or play ZEN while waiting!": "您加入了快速游戏 - 请等待结束然后加入下一局。在等待时，您可以选择旁观或游玩单人的禅意模式！",
      "you can change these and many other settings in CONFIG. have fun!": "您可以在设置中更改这些和许多其他设置。祝您玩得愉快！",
      "GAME IN PROGRESS, GOOD LUCK!": "游戏正在进行中，祝你好运!",
      "Super Lobby Mode Engaged - congratulations on hitting 100 players! Joins and leaves will be suppressed, and the winner of games in this room will earn a special profile badge!": "超级房间模式开启--达到了100名玩家! 进退房消息将暂时关闭，本局游戏的赢家将获得一枚特殊的个人资料徽章!",
      "Super Lobby Mode Disengaged": "超级房间模式解除",
      "click to switch to PLAYERS": "点击以切换到游玩模式",
      "SPECTATE": "旁观",
      "enter room id or url and hit enter...": "输入房间编号或网址并单击回车...",
      "you just joined QUICK PLAY - the next game will start automatically. please wait just a moment longer!": "你刚刚加入了快速游戏——下一场游戏即将开始。请稍等片刻",
      "PLAYERS (": "玩家数 （",
        //自定义游戏相关文本
      "CUSTOM GAME": "自定义游戏",
      "create public and private rooms to play by your rules": "创建公共和私人房间，按照您的规则进行游戏",
      "PUBLIC ROOM": "公共房间",
      "create a public room anyone can join": "创建一个任何人都可以加入的公共房间",
      "PRIVATE ROOM": "私人房间",
      "create a private room for you and friends": "为你和朋友创建一个私人房间",
      "Welcome to chat! Please remember to be civil to your opponents.": "欢迎来到聊天室! 请文明交流。",
      "ROOM": "房间",
      "MATCH": "比赛",
      "GAME": "对局",
      "room name": "房间名",
      "player limit": "人数限制",
      "auto start": "自动开始",
      "allow anonymous users to join": "允许匿名用户加入",
      "allow unranked users to play": "允许未定段用户进行游戏",
      "RANK LIMIT": "段位限制",
      "limit by top rank": "按最高段位限制",
      "music": "音乐",
      "GENERAL": "一般设置",
      "gamemode": "对局模式",
      "first to (FT)": "争先（FT）",
      "win by (WB)": "争胜（WB）",
      "stock": "命数",
      "versus": "竞争",
      "[2 - ∞ players] a battle royale! who can survive the longest?": "[2-∞名玩家]一场大混战！谁能活得最久？",
      "PRACTICE": "练习",
      "[2 players] a mode to practice with a friend": "[2名玩家]一个与朋友一起练习的模式",
      "EXPERIMENTAL": "实验选项",
      "garbage passthrough": "垃圾行穿透",
      "limited": "限制",
        "LIMITED":"限制",
      "ZERO": "无",
      "opposing attacks in transit always cancel eachother out": "发送过程中的对立攻击总是相互抵消的。",
      "opposing attacks in transit cancel out while garbage is flying": "发送过程中的对立攻击能被抵消，垃圾行偶尔会飞来。",
      "CONSISTENT": "相容",
      "opposing attacks in transit cancel out except when garbage is flying": "发送过程中的的对立攻击能被抵消，除非是在垃圾行横飞的时候",
      "FULL": "全数",
      "opposing attacks in transit do not cancel eachother out": "发送过程中的对立攻击不会相互抵消",
      "game presets": "对局预设",
      "custom": "定制",
      "default": "默认设置",
      "tetra league": "tetra 联赛",
      "CLASSIC": "经典",
      "ARCADE": "街机",
      "ENFORCED DELAYS": "延迟块",
      "TETR.IO's premier room settings. optimized for battles with large groups or duels against friends and foes alike!": "TETR.IO的首要房间设置。为与大型团体的战斗或与朋友和敌人的决斗而优化!",
      "settings copied directly from TETR.IO's matchmaking rooms! margin times and match goals are shifted slightly with duels in mind.": "与 TETRA 联赛完全相同的设置！考虑到规则为单挑，临界时间与获胜条件与默认设置有些许不同。",
      "an endurance-focused challenge of pure stacking intellect! almost every value is changed to imitate stacker games made many years ago.": "一个以耐力为重点的纯粹堆叠的智力挑战！为模仿多年前的方块游戏，几乎改变了所有参数。",
      "featuring innovative mechanics created for a popular stacker found in arcades, this preset puts a focus on smart stacking and mastery with its custom kick table!": "模仿创新性的街机方块机制，重点是策略堆叠与合理运用特殊的踢墙表。",
      "this preset introduces several forms of enforced handling which introduces a generous skill ceiling! puts a focus on efficient and consistent play, as opposed to deafeningly fast rounds.": "该预设限制了方块移动的延迟，稍微降低了水平上限。重点是高效且稳定的堆叠攻击上，而不是花里胡哨的开局互搏。",
      "settings copied directly from TETR.IO's quick play room!": "设置直接从TETR.IO的快速游戏中复制!",
      "random bag type": "随机BAG类型",
      "keep shuffling a bag of the 7 tetrominoes": "保持随机排列一包7块中包含所有种类的方块",
      "keep shuffling a bag of 2x the 7 tetrominoes": "保持随机排列一包14块中包含所有种类的方块各两块",
      "random with repetition protection": "具有重复保护的随机性",
      "alternate between 2 tetrominoes": "交替使用2种方块",
      "completely random generation": "完全随机生成",
      "allowed spins": "允许的旋转规则",
      "receive bonuses for spinning T-pieces": "旋转T块获得额外攻击",
      "receive bonuses for spinning all pieces": "旋转所有方块都可以获得额外攻击",
      "receive bonuses for spinning all pieces BUT attacks are halved except for T-SPINS": "旋转除T块以外的所有方块都可以获得额外攻击但攻击力减半",
      "everything is a spin because YEAH WHY NOT (O-spin SUPPORTED!)": "所有方块都能 SPIN，为什么不呢？（支持 O-Spin！）",
      "receive no spin bonuses": "旋转任何方块都没有额外攻击",
      "combo table": "连击表",
      "disable combo chaining": "禁止连击表",
      "TETR.IO's combo multiplier": "TETR.IO的连击倍增表",
      "classic guideline combo table": "经典规则连击表",
      "modern guideline combo table": "现代规则连击表",
      "allow 180 spins": "允许180度旋转",
      "kick table": "旋转系统",
      "the default natural rotation system with symmetric I-piece rotation": "默认的超级旋转系统和对称的I块旋转",
      "the standard natural rotation system": "默认的超级旋转系统",
      "SRS with more powerful 180 spins": "带有更强大的180度旋转的超级旋转系统",
      "novel rotation system by DR OCELOT": "DR OCELOT 的新型旋转系统",
      "the classic rotation system": "经典旋转系统",
      "rotation system used in arcade games": "在街机游戏中使用的旋转系统。",
      "permissive rotation system by WINTERNEBS": "WINTERNEBS 的七转八转旋转系统",
      "no kicks possible": "无法踢墙",
      "use hard drop": "允许硬降",
      "use NEXT queue": "允许查看下一个方块",
      "use HOLD queue": "允许查看暂存方块",
      "next pieces": "下一块",
      "show shadow piece": "显示阴影",
      "line clear ARE": "行数清除",
      "ARE": "ARE",
      "enforce below handling settings": "强制执行以下灵敏度设置",
        "enforced ARR": "强制ARR",
      "enforced DAS": "强制DAS",
      "enforced SDF": "强制SDF",
      "GRAVITY & MARGIN TIME": "重力和临界时间",
      "gravity": "重力",
      "gravity increase": "重力增量",
      "gravity margin time": "重力临界时间",
      "garbage multiplier": "垃圾行加成",
      "garbage margin time": "垃圾行临界时间",
      "garbage increase": "垃圾行增量",
      "lock delay": "锁定延迟",
      "garbage travel speed": "垃圾行飞行速度",
      "garbage cap": "单次垃圾行上限",
      "garbage cap increase": "单次垃圾行上限增量",
      "garbage cap max": "单次垃圾行最大上限",
      "garbage blocking": "垃圾行阻挡",
      "none": "无",
      "enable back-to-back chaining": "启用背靠背连锁增伤",
      "allow manual targeting": "允许手动选定目标",
      "enable clutch clears": "启用 clutch 消除",
      "disable lockout": "禁用锁定",
      "board width": "游戏区域宽度",
      "board height": "游戏区域高度",
      "WARNING: server restarting soon!": "警告：服务器即将重启",
      "COMBO BLOCKING": "连击阻挡",
      "incoming garbage will be delayed and reduced on successive line clears": "连击可阻挡并抵消垃圾行",
      "LIMITED BLOCKING": "限制阻挡",
      "incoming garbage can be reduced only once per next immediate piece": "单个方块只能阻挡并抵消一次垃圾行",
      "incoming garbage cannot be blocked": "垃圾行无法阻挡或抵消",
        //房间列表相关文本
      "ROOM LISTING": "房间列表",
      "join public custom games": "加入公共自定义房间",
      "REFRESH": "刷新",
      "anons allowed:": "允许匿名：",
      ", unranked allowed:": "，允许未定段：",
      "YES": "是的",
      "NO": "不",
      "and below -": "及以下",
      "INGAME -": "在游戏中 -",
      "LOBBY -": "大厅 -",
      "pick a room to join!": "选择一个房间加入",
        //TETRA频道相关文本
      "TETRA CHANNEL": "TETRA频道",
      "leaderboards, replays and more": "排行榜、回放等",
      "VISIT THE TETRA CHANNEL SITE": "访问TETRA频道网站",
      "VIEW FULL LEADERBOARDS, COUNTRY LEADERBOARDS, USER PAGES AND MORE": "查看完整排行榜、地区排行榜、用户页面等",
      "LEADERBOARDS": "排行榜",
      "GLOBAL LEADERBOARDS FOR 40 LINES AND BLITZ": "40行竞速和闪电战模式的全球排行榜",
      "ME": "我的",
      "VIEW YOUR OWN RECORDS AND RECENT GAMES": "查看您自己的记录和最近的比赛",
      "PLAYERS": "玩家",
      "TETRA LEAGUE LEADERBOARDS AND XP": "TETRA联赛和经验值排行榜",
      "LIVE NOW": "正在直播",
      "TETRA NEWS": "TETRA新闻",
      "PLAY": "游玩",
      "RECENT": "最近",
      "VICTORY": "获胜",
      "DEFEAT": "落败",
      "BY LEAGUE RATING": "按联赛段位排名",
      "BY XP": "按经验值排名",
      "you forfeited": "你弃权了",
      "only the first 100 are shown. to see the full leaderboard, click VIEW FULL above.": "只显示前100名。要看完整的排行榜，请点击上面的查看完整排行榜。",
      "PIECES PLACED":"放置块数",
      "PIECES per SECOND":"每秒放置块数",
      "KEYS PRESSED":"按键数",
      "KEYS per PIECE":"按键每块",
      "OVERVIEW":"回顾",
      "STATS":"统计数据",
      "KEYS per SECOND":"每秒按键数",
      "HOLDS":"暂存数",
      "LINES per MINUTE":"每分钟行数",
      "maximum COMBO":"最大连击数",
      "maximum back-to-back chain":"最长背靠背连锁",
      "finesse %":"极简率",
      "finesse faults":"非极简操作",
      "FINAL TIME":"最终时间",
      "FINAL SCORE":"最终得分",
      "RESULTS":"比赛结果",
      "got a new personal best in 40 LINES with a time of":"在40行挑战中取得了新的个人最好成绩，时间为",
      "got a new personal best in BLITZ with a score of":"在闪电战中取得了新的个人最好成绩，得分为",
      "has become a":"成为了",
      "got a new personal best in 5,000,000 BLAST with a time of":"在5,000,000 BLAST中获得了新的个人最佳成绩，时间为",
      "received the":"取得了",
      "badge":"徽章",
      "achieved":"达成",
      "rank":"段位",
      "SCORES":"分数",
      "LATEST NEWS":"最新动态",
      "VIEW TETRA LEAGUE RECORD":"查看TETRA联赛回放",
      "VIEW PERSONAL BEST":"查看最好成绩",
      "VIEW ALL 40 LINES RECORDS":"查看全部的40行挑战回放",
      "Achieved":"达成于",
      "months":"月",
      "ago":"前",
      "VIEW ALL BLITZ RECORDS":"查看全部的闪电战回放",
      "VIEW ALL RECENT RECORDS":"查看全部的近期回放",
      "RECORD":"回放",
      "VIEW":"查看",
      "PLAY TIME":"游戏时长",
      "ONLINE GAMES":"游戏场次",
      "OF WHICH WINS":"获胜场次",
      "EXPAND":"展开",
      "":"",
      "":"",
      "":"",
      "":"",
      "":"",
      "":"",
      "":"",
      "":"",
        //举报相关文本
      "REPORT": "举报",
      "please choose a category to report": "请选择向TETR.IO管理员报告",
      "to the TETR.IO moderators for. ": "的违规原因",
      "repeatedly placing false reports may result in a ban.": "重复进行假举报可能会导致封禁。",
      "TOXICITY": "有害内容",
      "including, but not limited to toxicity, harassment, unsolicited direct messages, offensive content or bad language.": "包括但不限于有害内容、骚扰、未经请求的直接消息、冒犯性内容或粗言秽语",
      "CHEATING": "作弊",
      "including, but not limited to cheating, botting, hacking or otherwise breaking the game or getting an unfair advantage.": "包括但不限于作弊、使用机器人、黑客手段或其他破坏游戏或获得不公平优势的行为。",
      "MULTIACCOUNTING": "多个账户",
      "including, but not limited to smurfing, multiaccounting, boosting accounts, throwing games.": "包括但不限于：炸鱼、多开账户、恶意刷分、消极对局等",
      "NSFW/18+ CONTENT": "不宜公开浏览/18+内容",
      "including, but not limited to NSFW (not safe for work) avatars, banners, messages, etc.": "包括但不限于：不宜公开浏览的头像、横幅、信息等",
      "SPAM": "垃圾信息",
      "including, but not limited to advertising, message flood, etc.": "包括但不限于广告、刷屏等",
      "OTHER": "其他",
      "otherwise not listed abuse against the TETR.IO terms of service, such as users under the age of 13, or rules, such as impersonation.": "其他未列出的违反TETR.IO服务条款的滥用行为，包括但不限于未满13岁的用户、冒名顶替等。",
      "CANCEL": "取消",
        //连接错误相关文本
      "CONNECTION ERROR": "连接错误",
      "a connection error has occured and the connection was closed unexpectedly.": "发生了连接错误，连接被意外关闭。",
      "check your internet connection and configuration.": "检查你的互联网连接和配置。",
      "this disconnect was detected to be caused by your network connection.": "系统检测到本次掉线由你的网络连接引起。",
      "SOCKET ID": "帐户ID",
      "OK": "彳亍",
        //单人模式相关文本
      "SOLO": "单人模式",
      "challenge yourself and top the leaderboards": "挑战自我，登上排行榜的榜首。",
      "press START to begin playing": "按下开始游戏进行游玩",
        //40行竞速相关文本
      "40 LINES": "40行竞速",
      "complete 40 lines as quickly as possible": "尽快消除40行",
      "clear 40 lines in the shortest amount of time possible.": "以最短的时间内消除40行",
      "score doesn't matter here, just go for the world record!": "得分在这里并不重要，尽力争取世界纪录吧！",
      "PERSONAL BEST": "个人最佳",
      "OPTIONS": "选项",
      "pro mode": "专业模式",
      "alert on finesse fault": "非极简操作时播放音效提醒",
      "retry on finesse fault": "非极简操作时自动重新开始",
      "stride mode": "快速开局",
      "ADVANCED": "高级设置",
      "left counter slot 1": "左侧信息栏槽位1",
      "left counter slot 2": "左侧信息栏槽位2",
      "left counter slot 3": "左侧信息栏槽位3",
      "left counter slot 4": "左侧信息栏槽位4",
      "right counter slot": "右侧信息栏槽位",
      "DEFAULT": "默认设置",
      "use the default option": "使用默认设置",
      "EMPTY": "空",
      "leave this slot empty": "留空该槽位",
      "LINES": "行数",
      "TIME": "时间",
      "SCORE": "分数",
      "display the score in this slot": "在该槽位中显示得分",
      "SCORE (per piece)": "分数（每块）",
      "display the score and score per piece in this slot": "在该槽位中显示每次放置方块的得分",
      "STOPWATCH": "秒表",
      "display the time passed in this slot": "在该槽位中显示此时已用时长时间",
      "display the amount of cleared lines in this slot": "在该槽位中显示已消除的行数",
      "PIECES": "块",
      "display the amount of placed pieces and speed in this slot": "在该槽位中显示放置方块的数量和速度",
      "INPUTS": "输入",
      "display the amount of buttonpresses in this slot": "在该槽位中显示按键按压量",
      "FINESSE": "极简",
      "display your finesse in this slot": "在该槽位中显示你的极简率",
      "FINESSE (SMALLER)": "极简（较小）",
      "display your finesse in this slot (for use on the left-hand side)": "在该槽位中显示你的极简率（在左边显示）",
      "HOLD": "暂存",
      "display the amount of held pieces in this slot": "在该槽位中显示暂存过的方块数量",
      "ALL CLEARS": "全消",
      "display the amount of ALL CLEARS in this slot": "在该槽位中显示全消的次数",
      "display the time remaining in this slot": "在该槽位中显示剩余时间",
      "TIMER": "计时器",
      "LEVEL": "等级",
      "display the current level in this slot": "在该槽位中显示当前等级",
        //闪电战相关文本
      "BLITZ": "闪电战",
      "a two-minute race against the clock": "限时两分钟的打分挑战",
      "get as many points as possible within 2 minutes!": "在2分钟内获得尽可能多的分数！",
      "clear lines to level up and gain more points and speed!": "消行，升级，提速，打分！",
      "---default---": "---默认设置---",
      "START": "开始游戏",
        //
        //禅意模式相关文本
      "ZEN": "禅意模式",
      "relax or train in this neverending mode": "用于放松或训练的无尽模式",
      "relax or train in a neverending mode! your progress is stored across games.": "在无尽模式中放松或训练！进度会在离开时保存。",
      "adjust the feel or help train using the ZEN SIDEBAR.": "使用禅意模式侧边栏调整心境或进行训练",
      "you can undo and redo placements with CTRL+Z and CTRL+Y!": "你可以用CTRL+Z和CTRL+Y来撤销和重做!",
        //禅意模式局内的文本
      "hover to change settings": "悬停以改变设置",
      "LEVELING": "升级",
      "SPINS": "旋转方式",
      "KICK TABLE": "旋转系统",
      "COMBO TABLE": "连击表",
      "MULTIPLIER": "倍增",
      "CLASSIC GUIDELINE": "经典规则",
      "MODERN GUIDELINE": "现代规则",
      "GRAVITY": "重力",
      "SUBZERO": "反重力",
      "RELAXED": "弱重力",
      "ENGAGING": "中重力",
      "SPICY": "高重力",
      "STATIC": "超重",
      "DISPLAY": "显示",
      "VERSUS": "竞争",
      "SPEED": "速度",
      "EFFICIENCY": "效率",
      "GARBAGE": "垃圾行",
      "BACKFIRE 0.5X": "攻击反弹 0.5倍",
      "BACKFIRE 1X": "攻击反弹 1倍",
      "BACKFIRE 2X": "攻击反弹 2倍",
      "CHEESE LAYER": "奶酪层",
      "layer height": "层高",
      "timer interval": "定时器时间间隔",
      "CHEESE TIMER": "奶酪定时器",
      "UNCLEAR 0.5X": "无抵消 0.5倍",
      "UNCLEAR 1X": "无抵消 1倍",
      "UNCLEAR 2X": "无抵消 2倍",
      "static gravity": "静态重力",
      "cheese messiness %": "垃圾行混乱率",
      "NONE": "无",
        //自定义单机相关文本
      "CUSTOM": "自定义",
      "play, train and experiment by your rules": "按照自定义的规则进行游戏、训练和实验",
      "play as you wish! replays are not submitted.": "尽情游戏！回放不会被记录",
      "OBJECTIVE": "目标",
      "Disable combo chaining": "禁用连击增伤",
      "use random seed (overrides \"seed\")": "使用随机种子（覆盖'种子'）",
      "seed": "种子",
      "SURVIVAL": "生存",
      "mode": "模式",
      "garbage messiness %": "垃圾行混乱度",
      "do not spawn any garbage": "不生成任何垃圾行",
      "LAYER": "层数",
      "spawn garbage on a timer": "定期生成垃圾行",
      "keep a layer of garbage on the board": "保留一层垃圾行",
      "sticky layer": "粘连层",
      "minimum layer height": "最小层数高度",
      "infinite movement": "无限移动",
      "GRAVITY & LEVELLING": "重力和等级",
      "use levelling (overrides \"gravity\")": "使用等级系统（覆盖重力设置）",
      "use master levels": "使用MASTER等级",
      "starting level": "起始级别",
      "level speed": "等级速度",
      "use static levelling (overrides \"level speed\")": "使用静态级别(覆盖等级速度)",
      "level static speed": "静态等级速度",
      "base gravity": "基础重力",
      "allow retry": "允许重新开始",
      "recieve bonuses for spinning all pieces. non T-SPINS attacks are halved. pieces use 4-corner detection": "旋转所有方块可以获得额外攻击。非T旋攻击减半。方块使用四角检测",
      "key": "关键",//?
      "final score will be displayed": "最终得分将会显示",
      "final time will be displayed": "最终时间将会显示",
      "final line count will be displayed": "最终行数将会显示",
      "play infinitely": "无限制模式",
      "get to a set amount of lines to clear": "达到设定的消除行数",
      "play for a set amount of time to clear": "在设定的时间内进行游戏并尽可能消除方块",
      "get to a set amount of garbage lines to clear": "达到设定的垃圾行清除数",
      "TIMED": "计时模式",
      "count": "计数",
      "time": "时间",
      "topping out is OK": "堆到顶部也是可以的",//?
      "display objective behind board": "在游戏板块后面显示目标",
      "INTRO": "简介",
      "mission": "任务",
      "play countdown": "播放倒计时",
      "countdown count": "倒计时计数",
      "countdown interval":"倒计时间隔",
      "time before countdown": "倒计时开始前的等待时间",
      "time before start": "游戏开始前的等待时间",
      "zoom animation": "缩放动画",
      "NO ANIMATION": "没有动画",
      "display no animation": "不显示动画",
      "display a fast animation": "显示快速动画",
      "display a slow animation": "显示慢速动画",
      "CINEMATIC": "电影级动画",
      "display a very slow animation": "显示非常慢的动画",
      "META": "元",
      "enforce absolute line count": "强制执行绝对行计数",
      "display progress bar": "显示进度条",
      "display the time remaining in this slot (for TIMED objective)": "在这个槽位中显示此时剩余的时间（用于限时目标）",
      "GARBAGE CLEARED": "已清理垃圾行",
      "display the amount of garbage lines cleared in this slot": "在这个槽位中显示已清除的垃圾行数",
       //设置内文本
      "CONFIG": "设置",
      "tweak your": "调整您的",
      "experience": "体验",
       //键位文本
      "CONTROLS": "键位",
       "forfeit game": "退出游戏",
      "retry game": "重新开始",
      "open chat": "打开聊天框",
      "pick targeting strategy": "挑选目标策略",
      "move in menus": "移动菜单",
      "confirm in menus": "在菜单中确认",
      "back in menus": "返回菜单中",
      "open social overlay": "打开好友列表",
      "controllers can be set up in CUSTOM controls - just press the controller buttons you wish to bind.": "手柄键位可以在自定义中设置 - 只需点击想要更改的键位并按下你想绑定的按键。",
      "controller sensitivity": "按键灵敏度",
      "vibration intensity": "振动强度",
      "WEAK": "弱",
      "STRONG": "强",
      "LOW": "低",
      "HIGH": "高",
      "[NOT SET]": "[未设置]",
      "hover over a setting for more info": "将鼠标悬停在设置名称上查看详细说明",
      "change account settings": "更改账户设置",
      "targeting strategy 1": "锁定目标策略1",
      "targeting strategy 2": "锁定目标策略2",
      "targeting strategy 3": "锁定目标策略3",
      "targeting strategy 4": "锁定目标策略4",
      "press any key or button": "按任何按键以绑定键位",
      "click anywhere to remove the keybind": "点击任何地方都可以删除绑定的按键",
      "menus: up": "菜单：上",
      "menus: down": "菜单：下",
      "menus: left": "菜单：左",
      "menus: right": "菜单：右",
      "menus: confirm": "菜单：确定",
      "menus: back": "菜单：返回",
      "move falling piece left": "向左移动",
      "move falling piece right": "向右移动",
      "soft drop": "软降",
      "hard drop": "硬降",
      "rotate counterclockwise": "逆时针旋转",
      "rotate clockwise": "顺时针旋转",
      "rotate 180": "180度旋转",
      "swap hold piece": "暂存方块",
        //移动灵敏度文本
      "HANDLING": "移动灵敏度",
      "SLOW": "慢",
      "FAST": "快",
      "prevent accidental hard drops": "防止误操作硬降",
      "cancel DAS when changing directions": "改变方向时取消DAS",
      "RESET": "重置",
      "TEST": "测试",
        //音乐及音效相关文本
      "VOLUME & AUDIO": "音乐及音效",
      "MUSIC": "音乐",
      "SFX": "音效",
      "BGM": "音乐",
      "stereo": "立体声",
      "scroll to change volume": "鼠标滚轮调整音量",
      "mute music when hidden": "最小化窗口时静音",
      "hear next pieces": "下一块音效",
      "hear other players": "其他玩家的音效",
      "hear attacks": "攻击音效",
      "do not reset music when retrying": "重新开始时不重置音乐",
      "disable sound entirely": "关闭全部声音",
      "QUIET": "静",
      "LOUD": "响",
      "NO STEREO": "无立体声",
      "SUPER STEREO": "超级立体声",
      "TWEAK MUSIC": "曲库",
      "select how often you want each song to be picked here, or ban songs if you so desire. click a song's title to play it.": "选择你希望每首歌曲在这里被挑选的频率，或者如果你希望的话，可以禁止歌曲播放。",
       //局内设置相关文本
      "GAMEPLAY": "局内设置",
      "ACTION TEXT": "特殊攻击文本特效",
      "OFF": "关/零重力",
      "SOME": "部分",
      "ALL": "所有",
      "board bounciness": "框体弹性",
      "STIFF": "固定",
      "BOUNCY": "弹跳",
      "SHAKY": "抖动",
      "damage shakiness": "受击震动",
      "grid visibility": "网格能见度",
      "board visibility": "背景能见度",
      "TRANSPARENT": "透明",
      "shadow visibility": "影子能见度",
      "OPAQUE": "不透明",
      "board zoom": "场地尺寸",
      "FAR": "远",
      "NEAR": "近",
      "show duels side-by-side": "1v1时并排显示场地",
      "spin board when you T-spin": "T-Spin时旋转场地",
      "alert me when i KO someone": "KO对手时提示",
      "enable the fire meter": "启用火力计",
      "warn me when i'm in danger": "濒死警告",
      "colored shadow piece": "彩色影子",
        //视频与界面相关文本
      "VIDEO & INTERFACE": "视频与界面",
      "GRAPHICS": "图形",
      "MINIMAL": "极低",
      "MEDIUM": "中等",
      "ULTRA": "极高",
      "CACHING": "缓存",
      "OFF": "关",
      "BALANCED": "均衡",
      "AGGRESSIVE": "激进",
      "particle count": "特效粒子数量",
      "FEW": "少",
      "LOTS": "多",
      "background visibility": "背景能见度",
      "bloom filter power": "布隆过滤器",
      "chromatic aberration": "色差",
      "flashwave power": "闪光强度",
      "make": "使",
      "run slowly to keep other programs running smoothly": "较慢运行以防使其他程序卡顿",
      "render at a low resolution": "低分辨率渲染",
      "less precision on counters": "低精度计时器",
      "always simplify multiplayer thumbnails": "始终简化多人模式缩略图",
      "do not animate background in super lobbies": "禁用超级房间内滚动显示玩家",
      "no background in menus": "关闭菜单背景",
      "filter profanity in chat": "过滤聊天中的脏话",
      "hide chat when ingame": "游戏中隐藏聊天栏",
      "hide room IDs": "隐藏房间ID",
      "show emotes in chat": "显示聊天内的表情",
      "show animated emotes in chat": "显示聊天内的动态表情",
      "invert chat colors": "聊天栏反色",
      "darken screen behind chat": "聊天栏暗色背景",
      "keep replay tools open": "一直显示回放工具栏",
      "hide network warning icons": "隐藏网络警告图标",
      "warn me when the game is not focused": "焦点不在游戏时提醒",
      "show the welcome guide": "显示新玩家引导",
        //通知相关文本
      "NOTIFICATIONS": "通知",
      "show desktop notifications": "推送系统通知",
      "suppress notifications while ingame": "禁止游戏中的通知",
      "always play notification sounds at full volume": "总是以全音量提示音效",
      "NOTIFY ME WHEN A FRIEND GOES ONLINE": "好友上线时提醒",
      "INGAME": "在游戏中",
      "INGAME & DESKTOP": "在游戏中和桌面上",
      "NOTIFY ME WHEN A FRIEND GOES OFFLINE": "朋友下线时通知我",
      "NOTIFY ME WHEN A FRIEND SENDS ME A DIRECT MESSAGE": "当朋友向我发送直接信息时通知我",
      "NOTIFY ME WHEN SOMEONE INVITES ME TO A ROOM": "当有人邀请我去一个房间时，通知我",
      "OTHER NOTIFICATIONS": "其他通知",
      "NOTIFY ME WHEN A NON-FRIEND SENDS ME A DIRECT MESSAGE":"当陌生人直接给我发信息时通知我",
        //个性化相关文本
      "CUSTOMIZATION": "个性化",
      "use custom background image": "使用自定义背景图片",
        //导出设置文本
      "EXPORT SETTINGS": "导出设置",
      "download a .TTC file of your config you can drag into": "下载一个你的配置的.TTC文件，你可以拖到",
      "to import": "中导入",
        //加载文本
      "requesting orders…": "请求命令...",
      "requesting account data…": "正在请求账户数据···",
      "fetching TETRA LEAGUE data…": "获取TETRA 联赛数据中···",
      "joining room…": "加入房间中···",
      "leaving room…": "离开房间中···",
      "connecting to live servers…": "正在连接到服务器...",
      "SWITCHING SERVER": "正在切换服务器...",
      "SERVER SWITCHED": "服务器已切换",
      "YOU ARE ALREADY IN THE ROOM": "你已在该房间",
      "fetching records…":"获取记录中···",
      "fetching replay…":"正在获取回放···",
      //账户相关文本
      "ACCOUNT": "账户",
      "ORDER HISTORY": "历史订单",
      "view previous orders": "查看以前的订单",
      "SUPPORT OR GIFT": "支持或捐赠",
      "LOG OUT ALL": "登出所有",
      "AVATAR": "头像",
      "a nice, 2MB max. image to represent yourself, or a generic identicon if none is chosen.": "用一张漂亮的、最大2MB的图片来作为你自己的头像，如果没有选择的话，可以选择一个通用的标识。",
      "REMOVE": "移除",
      "CHANGE": "更改",
      "BANNER": "横标",
      "a nice, 2MB max. image to display behind your profile and": "一个漂亮的，最大2MB的图片，显示在你的个人资料后面，以及",
      "userpage": "个人空间",
      ". target resolution is 1920x240.": ",图片目标分辨率为1920x240",
      "ABOUT ME": "关于我",
      "COUNTRY": "地区",
      "PRIVACY": "隐私",
      "SAVE": "保存",
      "show total time played on my profile": "在我的个人资料中显示总游戏时长",
      "show # of online games won on my profile": "在我的个人资料中显示获胜的游戏对局数",
      "show # of online games played on my profile": "在我的个人资料中显示所玩的总游戏对局数",
      "show my country on my profile": "在我的个人资料中显示我的地区",
      "WHO CAN ADD ME AS FRIEND": "谁能加我为好友",
      "This does not apply retroactively.": "这并不具有追溯性。",
      "MY FRIENDS": "我的好友",
      "EVERYONE": "所有人",
      "WHO CAN SEE WHETHER I'M ONLINE": "谁能看到我是否在线",
      "e.g. \"Online\", \"Away\", \"Offline\". People who cannot see whether you're online cannot invite you to rooms either.": "举个例子\"在线\", \"离开\", \"离线\". 不能看到你是否在线的人也不能邀请你去房间。",
      "NOBODY": "没有人",
      "WHO CAN SEE WHAT I'M DOING": "谁能看到我在做什么",
      "e.g. \"Playing 40 LINES\", \"In TETRA LEAGUE queue\", \"In Menus\"": "举个例子 \"正在进行40行竞速\", \"正在进行TETRA 联赛\", \"在主菜单中\"",
      "WHO CAN SEE WHAT ROOM I'M IN": "谁能看到我在哪个房间",
      "e.g. \"In QUICK PLAY lobby\", \"In a public custom room\". People who can see what room you're in can also quickly join said room. Private rooms are always hidden.": "举个例子\"在快速游戏房间\", \"在公共自定义房间\". 能看到你在哪个房间的人也能迅速加入这个房间。私人房间总是隐藏的。",
      "WHO CAN SEND ME DIRECT MESSAGES": "谁可以直接给我发信息",
      "WHO CAN SEND ME INVITES TO ROOMS": "谁可以直接邀请我进房间",
      "USERNAME": "用户名",
      "this is the name you will show up to others as.": "这是你在别人面前显示的名字。",
      "EMAIL": "电子邮箱",
      "this email account will be used for secure account actions, like account recovery.": "这个电子邮件账户将被用于安全的账户操作，如账户恢复。",
      "you do not currently have an email set. if you lose your password, your account cannot be recovered!": "你目前没有设置电子邮件。如果你丢失了密码，你的账户就无法恢复了",
      "PASSWORD": "密码",
      "you can change the password used to log in here.": "你可以在这里更改用于登录的密码。",
      "TWO-FACTOR AUTHENTICATION": "双重身份验证",
      "two-factor authentication is": "双重认证",
      "NOT ENABLED": "未启用",
      "ENABLE": "启用",
      "RESET RECOVERY CODES": "重置恢复代码",
      "DISABLE": "暂停使用",
      "CONNECTIONS": "连接",
      "link other accounts with TETR.IO here, or remove them at any time.": "在此链接其他账户与TETR.IO，或随时删除它们。",
      "LINK": "链接",
      "REMOVE": "移除",
      "display publicly": "公开展示",
      "write a little something about yourself to display on": "写点关于你自己的东西，展示在",
      "your userpage": "你的个人空间",
      ", or leave this blank to disable. simple markdown allowed.": "，或留空禁用。允许简单的标记。",
      "Direct messages from non-friends show up on the NON-FRIENDS tab in the social overlay.": "来自陌生人的直接信息显示在社交叠加中的\"陌生人\"标签上。",
      "To be able to send you an invite, others will also need to be able to see whether you're online.": "为了能够向你发出邀请，其他人也需要能够看到你是否在线。",
      "ENABLE TWO-FACTOR AUTHENTICATION": "启用双重身份验证",
      "generating tokens…": "正在生成令牌…",
      "scan the following QR code with your favourite authenticator app (like AUTHY or GOOGLE AUTHENTICATOR), then enter the six-digit code into the box below to enable two-factor authentication": "使用您喜欢的验证器应用程序（如AUTHY或GOOGLE authenticator）扫描以下二维码，然后在下面的框中输入六位代码以启用双重身份验证",
        //关于相关文本
      "ABOUT": "关于",
      "all about": "所有关于",
      "thank you for playing": "感谢你游玩",
        //其他文本
      "pick a game mode": "选择一个游戏模式",
      "KEEP HOLDING TO FORFEIT": "长按退出",
      "KEEP HOLDING TO RETRY": "长按重试",
      "WINNER!": "胜利！",
      "OUT OF FOCUS": "失去焦点",
      "click to return to TETR.IO": "点击回到TETR.IO",
      "replay will not be saved": "回放将不会被保存",
      "MANUAL": "手册",
      "WINNER THIS ROUND": "本轮胜者",
      "bgm": "音乐",
      "TETR.IO DESKTOP should open soon!": "TETR.IO 桌面版应该很快就会打开!",
      "you can close this tab once it has opened": "你可以在该标签打开后关闭它",
      "WHAT'S NEW": "更新内容：",
      "ALL PATCH NOTES": "完整更新日志",
      "COOL!": "酷诶！",
      "CLOSE": "关闭",
      "BACK": "返回",
      "HOME": "主页",
      "EXIT": "退出",
      "welcome to ": "欢迎来到",
      "an update is required to connect to multiplayer servers. click here to update!": "需要更新以连接到多人游戏服务器。点击这里进行更新！",
        //包含特殊文字
      "Ǳ LEADERBOARDS": "Ǳ 排行榜",
      "Ǳ VIEW FULL": "Ǳ 查看完整排行榜",
      "Ǳ VIEW FULL PROFILE": "Ǳ 查看完整资料",
      "Ǳ MY PAGE": "Ǳ 我的空间",
      "ǹ REMOVE": "ǹ 移除",
      "ǹ CHANGE": "ǹ 更改",
      "ǹ SAVE": "ǹ 保存",
      "ǹ CHANGE": "ǹ 更改",
        //好友系统相关文本
      "PEOPLE": "好友",
      "In a": "在一场",
      "In a private": "在一场私人的",
      "custom room": "自定义房间",
      "game": "对局",
      "Spectating a": "旁观一场",
      "Blocked": "拉黑",
      "UNBLOCK": "解除拉黑",
      "ONLINE": "在线",
      "lobby": "大厅",
      "GLOBAL": "全球",
      "FRIEND": "加为好友",
      "ANONYMOUS": "匿名",
      "If someone outside of your friends list messages you, they'll appear here.": "如果有在你好友名单之外的人给你发信息，他们会出现在这里。",
      "Not connected to online servers. Sit tight, we'll try to reconnect you in the background.": "没有连接到在线服务器。稍等片刻，我们会尝试在后台进行重连。",
      "In Menus": "在主菜单中",
      "appear as usual": "表示你一切正常",
      "AWAY": "离开",
      "appear away, unless you're offline or busy": "显示离开，表示你不在线或很忙",
      "BUSY": "正忙",
      "appear busy, unless you're offline. receive no notifications. always enabled in TETRA LEAGUE (unless you're invisible)": "显示很忙，除非你是离线的。不会收到任何通知。在TETRA 联赛中总是启用（除非你隐身了）",
      "INVISIBLE": "隐身",
      "appear offline at all times": "始终处于离线状态",
      "REPLAY": "回放",
      "LIVE": "直播",
      "grid": "网格",
      "You forfeited a ranked match": "你放弃了一场排位赛",
      "You have been awarded a loss for this match. Please ensure you have the time and internet connection to play! Repeated forfeits are punished (and will be automatically punished in the future). Thank you for understanding!": "你在这场比赛中被判为失败。请确保你有充裕的时间和良好的网络连接来进行比赛! 屡次弃权将受到惩罚（今后将自动受到惩罚）。感谢您的理解!",
      "Spectating a private": "旁观一场私人",
      "friends list": "好友列表",
      "has added you to their": "已将您加入到TA的",
      "has": "已经",
      "friended you back": "互相加为好友",
      "Offline": "离线",
      "invited you to": "邀请你",
      "Ending a private": "等待一场私人",
      "Please be civil. Staff will never ask for your credentials.": "请文明交流。官方永远不会索要您的个人信息。",
      "ONLINE": "在线",
      "Away": "离开",
      "Playing": "正在玩",
      "Busying": "正忙",
      "has come online": "上线了",
      "online now": "在线",
      "Ending a": "等待一场",
      "You haven't blocked anyone yet.": "你还没有拉黑任何人。",
      "BLOCKED": "黑名单",
      "Nobody's online right now": "现在没有人在线",
      "connected to server": "连接到服务器",
      "Ending an online": "等待一场在线",
      "In an ONLINE": "在一场在线",
        //错误相关文本
      "DEVELOPMENT BUILD": "开发版本",
      "if you have the feeling you're not supposed to be here, get out": "如果你觉得你不应该在这里，那就出去吧",
      "error loading TETR.IO": "加载TETR.IO出错",
      "we support the following browsers:": "我们支持以下浏览器：",
      "using TETR.IO desktop? this usually means something's very wrong (usually at TETR.IO's side). hit the button below to reload.": "使用TETR.IO的桌面？这通常意味着有些东西很不对劲（通常在TETR.IO这边）。点击下面的按钮重新加载。",
      "RELOAD": "重新加载",
      "TETR.IO requires WEBGL": "TETR.IO需要WEBGL",
      "it seems WEBGL is disabled in your browser. WEBGL is required for the game to render properly.": "看来你的浏览器禁用了WEBGL。游戏需要WEBGL才能正常渲染。",
      "please check your browser settings to ensure HARDWARE ACCELERATION is enabled in your browser, then try again. if that doesn't work, try upgrading your browser.": "请检查您的浏览器设置，确保您的浏览器启用了硬件加速功能，然后再试一次。如果不行，请尝试升级您的浏览器。",
      "TETR.IO DESKTOP is automatically set up to bring the smoothest experience, with far better performance and less setup hassle. install it with the button below!": "TETR.IO DESKTOP的自动设置带来了最流畅的体验，具有更好的性能和更少的设置麻烦。用下面的按钮安装它!",
      "already on desktop? you may need to restart your device.": "使用的已经是桌面版了？你可能需要重新启动设备。",
      "GET TETR.IO DESKTOP!": "获取 TETR.IO 桌面版!",
      "this ban only covers your network (IP). your account is": "这个禁令只包括你的网络（IP）。你的账户是",
      "not banned": "没有被禁用的",
      "! please turn off any VPN/proxy, and/or try from a different network. in most cases, ": "请关闭任何VPN/代理，尝试不同的网络环境，多数情况下可解决",
      "support cannot help you here.": "赞助对解除封禁无效。",
      "if you believe you were banned in error,": "如果你认为你被封禁是错误的、",
      "YOU HAVE BEEN BLOCKED FROM TETR.IO": "您已被阻止进入 TETR.IO 网站",
      "A connection error has occured": "发生了一个连接错误"
    };

    // 定义一个函数以替换页面上的文本
    function replaceText() {
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false);
        while (walker.nextNode()) {
            const node = walker.currentNode;
            let text = node.nodeValue.trim();
            if (textMap[text]) {
                if (shouldExclude(node)) {
                    continue;
                }
                node.nodeValue = textMap[text];
            }
        }
    }

    // 检查给定的节点及其祖族元素是否包含应该排除的元素
    function shouldExclude(node) {
        let currentNode = node;
        while (currentNode) {
            if (currentNode.nodeType === Node.ELEMENT_NODE && (currentNode.getAttribute("data-uid") === "5f4ca7f5fdcc602e78a65bba" || currentNode.classList.contains("user")||(currentNode.matches('.leagueplayer_name') ||
                    currentNode.classList.contains('primary')|| currentNode.classList.contains('uniflex-item')||currentNode.getAttribute("id") === "breadcrumbs") )) {
                return true;
            }
            currentNode = currentNode.parentNode;
        }
        return false;
    }
   // 当脚本第一次加载时替换页面上的文本
    replaceText();

  // 使用MutationObserver在页面更新时自动替换文本
    const observer = new MutationObserver(replaceText);
    observer.observe(document.body, { childList: true, subtree: true });
})();
