// ==UserScript==
// @name         TETR.IO中文翻译自动挡
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  将TETR.IO中的内容翻译成中文并自动刷新保证翻译内容基本完成，对性能可能有一点影响
// @match        https://tetr.io/
// @match        https://ch.tetr.io/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Define the text mapping table
    const textMap = {
     "JOIN": "加入",
      "CONFIG": "设置",
      "CONTROLS": "键位",
      "HANDLING": "灵敏度",
      "ABOUT": "关于",
      "BACK": "返回",
      "ACCOUNT": "用户",
      "VOLUME & AUDIO": "音量与音效",
      "MUSIC": "背景音乐",
      "MULTIPLAYER": "多人模式",
      "SOLO": "单人模式",
      "TETRA CHANNEL": "TETRA频道",
      "play online with friends and foes": "和你的好友或者陌生人在线游戏",
      "KEEP HOLDING TO FORFEIT": "长按退出",
      "KEEP HOLDING TO RETRY": "长按重试",
      "HOME": "主页",
      "EXIT": "退出",
      "welcome to ": "欢迎来到",
      "an update is required to connect to multiplayer servers. click here to update!": "需要更新以连接到多人游戏服务器。点击这里进行更新！",
      "challenge yourself and top the leaderboards": "挑战自我，登上排行榜的榜首。",
      "leaderboards, replays and more": "排行榜、重播等等",
      "tweak your": "调整您的",
      "experience": "体验",
      "all about": "所有关于",
      "ANONYMOUS": "匿名",
      "pick a game mode": "选择一个游戏模式",
      "40 LINES": "40行挑战",
      "complete 40 lines as quickly as possible": "尽快完成40行消除",
      "BLITZ": "限时挑战",
      "a two-minute race against the clock": "限时两分钟的挑战",
      "ZEN": "禅模式",
      "relax or train in this neverending mode": "在这个无尽模式中放松或训练",
      "CUSTOM": "自定义",
      "play, train and experiment by your rules": "按照您的规则进行游戏、训练和实验",
      "TETRA LEAGUE": "TETRA 联赛",
      "fight players of your skill in ranked duels": "在排名对决中与水平相当的玩家对战",
      "QUICK PLAY": "快速游戏",
      "jump into a currently ongoing match": "加入正在进行的比赛",
      "CUSTOM GAME": "自定义游戏",
      "create public and private rooms to play by your rules": "创建公共和私人房间，按照您的规则进行游戏",
      "ROOM LISTING": "房间列表",
      "join public custom games": "加入公共自定义房间",
      "VISIT THE TETRA CHANNEL SITE": "访问TETRA频道网站",
      "VIEW FULL LEADERBOARDS, COUNTRY LEADERBOARDS, USER PAGES AND MORE": "查看完整排行榜、国家及地区排行榜、用户页面等等",
      "LEADERBOARDS": "排行榜",
      "GLOBAL LEADERBOARDS FOR 40 LINES AND BLITZ": "40行挑战和限时挑战的全球排行榜",
      "ME": "我的",
      "VIEW YOUR OWN RECORDS AND RECENT GAMES": "查看您自己的记录和最近的比赛",
      "PLAYERS": "玩家",
      "TETRA LEAGUE LEADERBOARDS AND XP": "TETRA联赛排行榜和经验值排行榜",
      "LIVE NOW": "正在直播",
      "TETRA NEWS": "TETRA新闻",
      "ANONYMOUS USERS MAY NOT ENTER TETRA LEAGUE": "匿名玩家无法进入TETRA联赛",
      "PLAY": "游玩",
      "total players": "总玩家数",
      "games played": "对局场数",
      "hours played": "总游戏时长",
      "welcome to TETR.IO": "欢迎来到TETR.IO",
      "puzzle together in this modern yet familiar online stacker. play against friends and foes all over the world, or claim a spot on the leaderboards - the stacker future is yours!": "在这个现代而又熟悉的在线堆叠游戏中解谜。与世界各地的朋友和对手对战，或者在排行榜上占据一席之地——堆叠的未来就在您手中！",
      "enter a username to join, or leave it blank to get a random one": "输入用户名加入游戏，或者留空以获取随机用户名",
      "by joining, you accept the": "加入即表示您接受",
      "terms of use": "使用条款",
      "privacy policy": "隐私政策",
      "and": "和",
      "rules": "规则",
      "TETR.IO is in ALPHA. please report bugs when you see them!": "TETR.IO 处于 ALPHA 阶段，请在发现问题时报告错误！",
      "good to see you again!": "很高兴再次见到你",
      "the username": "这个用户名",
      "is registered. please enter your password to log in": "已经被注册了，请输入你的密码来登录",
      "I FORGOT": "忘记密码",
      "LOGIN": "登录",
      "forgot your password?": "忘记了您的密码？",
      "if you have an email address associated with your account, you can reset your password by entering your email.": "如果您的账户关联有电子邮件地址，您可以通过输入您的电子邮件来重置密码。",
      "REQUEST RESET": "请求重置密码",
      "password incorrect": "密码错误",
      "WHAT'S NEW": "有什么新内容",
      "ALL PATCH NOTES": "所有的更新日志",
      "COOL!": "酷！",
      "welcome back to TETR.IO!": "欢迎回到TETR.IO!",
      "is this you?": "这是你吗？",
      "LOG OUT": "退出登录",
      "CLOSE": "关闭",
      "this user is playing anonymously": "该用户正在匿名游戏",
      "games won": "获胜次数",
      " IN QUEUE - ": "在队列中 -",
      "IN GAME": "在比赛中",
      "ENTER MATCHMAKING": "进入匹配",
      "LEAVING EARLY IS PUNISHED": "早退将受到惩罚",
      "HOW DOES IT WORK?": "规则是什么？",
      "enter matchmaking and you will be matched up with a player of similar skill in a game of 1v1 VERSUS.": "进入匹配，您将与一个水平相似的玩家匹配，进行一场1对1的对战游戏。",
      "win games to gain TR and rank up! you must play at least 10 games to see your TR. to get a RANK and enter the GLOBAL LEADERBOARDS, keep playing consistently.": "获胜可以获得TR并晋升段位！您必须至少玩10局才能看到您的TR。要获得段位并进入全球排行榜，请持续进行游戏。",
      "if you leave the game early at any point, you will be awarded a loss. go conquer the ranks!": "如果您在任何时候提前离开游戏，您将会被判定为失败。去征服排行榜吧！",
      "LEADERBOARDS": "排行榜",
      "estimated queue time: ": "预计等待时间：",
      "CHAT": "聊天",
      "Welcome to Quick Play chat! Please remember to be civil to your opponents - chat is actively monitored.": "欢迎来到快速游戏聊天室！请记得对你的对手保持礼貌——聊天记录将被积极监控。",
      "left the room": "离开房间",
      "joined the room": "加入房间",
      "disconnected": "断开连接",
      "started the game": "开始游戏",
      "SPECTATING": "旁观中",
      "CURRENTLY INGAME": "当前正在游戏中",
      "game finished": "游戏结束",
      "welcome to ": "欢迎来到",
      "is a free familiar yet fast-paced online stacker in the same genre as tetris, and played by millions across the globe.": "是一款免费的在线益智游戏，游戏风格与俄罗斯方块相似，速度却更快，全球有数百万玩家在玩。",
      "hover for more info!": "把鼠标悬停在这里以获取更多信息！",
      "your currently set keybinds are:": "您当前设置的按键绑定是：",
      "PLAYING": "游玩",
      "click to switch to SPECTATORS": "点击以切换到旁观者模式。",
      "click to copy url": "点击这里复制链接",
      "EDIT": "退出",
      "you just joined QUICK PLAY - you will play in the next game in this lobby. please wait for the current game to finish. feel free to spectate or play ZEN while waiting!": "您刚刚加入了快速游戏 - 您将在此游戏房间中的下一场比赛中参加。请等待当前比赛结束。在等待时，可以自由选择旁观或玩“禅”模式！",
      "you can change these and many other settings in CONFIG. have fun!": "您可以在“设置”中更改这些和许多其他设置。祝您玩得愉快！",
      "clear 40 lines in the shortest amount of time possible.": "以最短的时间内消除40行方块",
      "score doesn't matter here, just go for the world record!": "得分在这里并不重要，尽力争取世界纪录吧！",
      "PERSONAL BEST": "个人最佳",
      "OPTIONS": "选项",
      "pro mode": "高级模式",
      "alert on finesse fault": "出现非极简操作时提醒音效。",
      "retry on finesse fault": "出现非极简操作时重新开始",
      "stride mode": "快速重开",
      "ADVANCED": "高级设置",
      "left counter slot 1": "左侧计数器插槽1",
      "left counter slot 2": "左侧计数器插槽2",
      "left counter slot 3": "左侧计数器插槽3",
      "left counter slot 4": "左侧计数器插槽4",
      "right counter slot": "右侧计数器插槽",
      "DEFAULT": "默认设置",
      "use the default option": "使用默认设置",
      "EMPTY": "空",
      "leave this slot empty": "将此插槽留空",
      "LINES": "行数",
      "TIME": "时间",
      "get as many points as possible within 2 minutes!": "在2分钟内获得尽可能多的分数！",
      "clear lines to level up and gain more points and speed!": "消除行数以升级并获得更多分数和速度！",
      "---default---": "---默认设置---",
      "START": "开始游戏",
      "relax or train in a neverending mode! your progress is stored across games.": "在无尽模式中放松或训练！您的进度将实时保存。",
      "adjust the feel or help train using the ZEN SIDEBAR.": "使用“禅”侧边栏调整手感或进行训练",
      "REPORT": "举报",
      "please choose a category to report": "请选择要向TETR.IO管理员报告",
      "to the TETR.IO moderators for. ": "的违规原因",
      "repeatedly placing false reports may result in a ban.": "重复进行假举报可能会导致封禁。",
      "TOXICITY": "有害内容",
      "including, but not limited to toxicity, harassment, unsolicited direct messages, offensive content or bad language.": "包括但不限于有害内容，骚扰，未经请求的直接消息，冒犯性内容或粗言秽语",
      "GUIDELINE": "指引",
      "GAME IN PROGRESS, GOOD LUCK!": "游戏正在进行中，祝你好运!",
      "Super Lobby Mode Engaged - congratulations on hitting 100 players! Joins and leaves will be suppressed, and the winner of games in this room will earn a special profile badge!": "超级大厅模式启动--恭喜你集齐了100名玩家! 加入和离开将被限制，在这个房间里的游戏的赢家将获得一个特殊的个人资料徽章!",
      "Super Lobby Mode Disengaged": "超级大厅模式解除",
      "move falling piece left": "向左移动",
      "move falling piece right": "向右移动",
      "soft drop": "软降",
      "hard drop": "硬降",
      "rotate counterclockwise": "逆时针旋转",
      "rotate clockwise": "顺时针旋转",
      "rotate 180": "180度旋转",
      "swap hold piece": "暂存方块",
      "RECENT": "最近",
      "YOU FORFEITED": "你放弃了",
      "VICTORY": "获胜",
      "DEFEAT": "落败",
      "BY LEAGUE RATING": "按联赛段位排名",
      "BY XP": "按经验值排名",
      "only the first 100 are shown. to see the full leaderboard, click VIEW FULL above.": "只显示前100名。要看完整的排行榜，请点击上面的查看完整排行榜。",
      "Ǳ VIEW FULL": "查看完整排行榜",
      "Ǳ VIEW FULL PROFILE": "查看完整资料",
      "FRIEND": "加为好友",
      "CHEATING": "作弊",
      "including, but not limited to cheating, botting, hacking or otherwise breaking the game or getting an unfair advantage.": "包括但不限于作弊、使用机器人、黑客手段或其他破坏游戏或获得不公平优势的行为。",
      "MULTIACCOUNTING": "多个账户",
      "including, but not limited to smurfing, multiaccounting, boosting accounts, throwing games.": "包括，但不限于，炸鱼，多账户，恶意刷分，消极对局",
      "NSFW/18+ CONTENT": "色情淫秽内容/18+内容",
      "including, but not limited to NSFW (not safe for work) avatars, banners, messages, etc.": "包括但不限于有关色情淫秽的头像、横幅、信息等内容。",
      "SPAM": "垃圾信息",
      "including, but not limited to advertising, message flood, etc.": "包括但不限于广告、复读机等行为。",
      "OTHER": "其他",
      "otherwise not listed abuse against the TETR.IO terms of service, such as users under the age of 13, or rules, such as impersonation.": "其他未列出的违反TETR.IO服务条款的滥用行为，包括但不限于未满13岁的用户，冒名顶替等。",
      "CANCEL": "取消",
      "click to switch to PLAYERS": "点击以切换到游玩模式",
      "SPECTATE": "旁观",
      "enter room id or url and hit enter...": "输入房间编号或网址并单击回车...",
      "CONNECTION ERROR": "连接错误",
      "a connection error has occured and the connection was closed unexpectedly.": "发生了一个连接错误，并且连接被意外关闭。",
      "check your internet connection and configuration.": "检查你的互联网连接和配置。",
      "this disconnect was detected to be caused by your network connection.": "该断开连接被检测到是由你的网络连接引起的。",
      "SOCKET ID": "帐户ID",
      "OK": "彳亍",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": "",
      "": ""
    };

    // Define a function to replace text on the page
    function replaceText() {
        const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, null, false);
        while (walker.nextNode()) {
            const node = walker.currentNode;
            let text = node.nodeValue.trim();
            if (textMap[text]) {
                node.nodeValue = textMap[text];
            }
        }
    }

    // Replace text on the page when the script is first loaded
    replaceText();

    // Use a MutationObserver to automatically replace text when the page is updated
    const observer = new MutationObserver(replaceText);
    observer.observe(document.body, { childList: true, subtree: true });
})();
